---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        stack.okteto.com/name: identity-socializer
        stack.okteto.com/service: api
    spec:
      containers:
      - name: api
        image: $OKTETO_BUILD_API_IMAGE
        imagePullPolicy: Always
        env:
        - name: IDENTITY_SOCIALIZER_CONTENT_DISCOVERY_URL
          value: http://api.content-discovery-luiscusihuaman:9000
        - name: IDENTITY_SOCIALIZER_DB_BASE
          value: identity_socializer
        - name: IDENTITY_SOCIALIZER_DB_HOST
          value: db
        - name: IDENTITY_SOCIALIZER_DB_PASS
          value: identity_socializer
        - name: IDENTITY_SOCIALIZER_DB_PORT
          value: "5432"
        - name: IDENTITY_SOCIALIZER_DB_USER
          value: identity_socializer
        - name: IDENTITY_SOCIALIZER_ENVIRONMENT
          value: dev
        - name: IDENTITY_SOCIALIZER_HOST
          value: 0.0.0.0
        - name: IDENTITY_SOCIALIZER_MONGO_HOST
          value: mongodb://mongo-db.identity-socializer-luiscusihuaman
        - name: IDENTITY_SOCIALIZER_PORT
          value: "8000"
        - name: IDENTITY_SOCIALIZER_RELOAD
          value: "True"
---
apiVersion: v1
kind: Service
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: api
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
