---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: identity-socializer-luiscusihuaman
spec:
  replicas: 1
  selector:
    matchLabels:
      stack.okteto.com/name: identity-socializer
      stack.okteto.com/service: db
  serviceName: db
  template:
    metadata:
      labels:
        stack.okteto.com/name: identity-socializer
        stack.okteto.com/service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: identity_socializer
            - name: POSTGRES_PASSWORD
              value: identity_socializer
            - name: POSTGRES_USER
              value: identity_socializer
          image: postgres:13.8-bullseye
          imagePullPolicy: IfNotPresent
          name: db
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - identity_socializer
            failureThreshold: 40
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: identity-socializer-db-data
              subPath: identity-socializer-db-data
      volumes:
        - name: identity-socializer-db-data
          persistentVolumeClaim:
            claimName: identity-socializer-db-data
---
apiVersion: v1
kind: Service
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: db
spec:
  selector:
    stack.okteto.com/name: identity-socializer
    stack.okteto.com/service: db
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
#apiVersion: batch/v1
#kind: Job
#metadata:
#  namespace: identity-socializer
#  name: identity-socializer-migrator
#spec:
#  ttlSecondsAfterFinished: 100
#  template:
#    spec:
#      containers:
#      - name: migrator
#        image: identity_socializer:latest
#        command:
#        - "alembic"
#        - "upgrade"
#        - "head"
#        resources:
#          limits:
#            memory: "200Mi"
#            cpu: "250m"
#        env:
#        - name: "IDENTITY_SOCIALIZER_DB_HOST"
#          value: "identity-socializer-db-service"
#      initContainers:
#      - name: wait-for-db
#        image: toschneck/wait-for-it:latest
#        command: ["./wait-for-it.sh", "-t", "60", "db-service:5432"]
#      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    stack.okteto.com/name: identity-socializer
    stack.okteto.com/service: migrator
  name: migrator
  namespace: identity-socializer-luiscusihuaman
spec:
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: migrator
        job-name: migrator
    spec:
      containers:
        - args:
            - alembic
            - upgrade
            - head
          env:
            - name: IDENTITY_SOCIALIZER_DB_BASE
              value: identity_socializer
            - name: IDENTITY_SOCIALIZER_DB_HOST
              value: db
            - name: IDENTITY_SOCIALIZER_DB_PASS
              value: identity_socializer
            - name: IDENTITY_SOCIALIZER_DB_PORT
              value: "5432"
            - name: IDENTITY_SOCIALIZER_DB_USER
              value: identity_socializer
          image: $OKTETO_BUILD_API_IMAGE
          imagePullPolicy: IfNotPresent
          name: migrator
      restartPolicy: Never
---
