---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
        stack.okteto.com/name: identity-socializer
        stack.okteto.com/service: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          imagePullPolicy: Always
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-db
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: ""
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: ""
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin@admin.com"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "admin"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: mongo-express
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: mongo-express
#  namespace: identity-socializer-luiscusihuaman
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: mongo-express.identity-socializer-luiscusihuaman.okteto.net
#      http:
#        paths:
#          - backend:
#              service:
#                name: mongo-express
#                port:
#                  number: 8081
#            path: /
#            pathType: ImplementationSpecific
