---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        stack.okteto.com/name: identity-socializer
        stack.okteto.com/service: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8.0
          imagePullPolicy: Always
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: identity-socializer-luiscusihuaman
  name: pgadmin
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: pgadmin
#  namespace: identity-socializer-luiscusihuaman
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: pgadmin.identity-socializer-luiscusihuaman.okteto.net
#       http:
#        paths:
#          - backend:
#              service:
#                name: pgadmin
#                port:
#                  number: 5050
#            path: /
#            pathType: ImplementationSpecific
