version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      IDENTITY_SOCIALIZER_RELOAD: "True"
  db:
    ports:
      # Exposes database port.
    - "5432:5432"
  mongo-db:
    ports:
      # Exposes database port.
    - "27017:27017"
