"""Create a baseline migrations

Revision ID: 847eee4ea866
Revises: 2b7380507a71
Create Date: 2023-09-21 17:33:04.478822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "847eee4ea866"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("bio_msg", sa.String(length=200), nullable=True),
        sa.Column("profile_photo_id", sa.String(length=200), nullable=True),
        sa.Column("blocked", sa.Boolean(), nullable=False, default=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
