"""Create a baseline migrations

Revision ID: 847eee4ea866
Revises: 2b7380507a71
Create Date: 2023-09-21 17:33:04.478822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "847eee4ea866"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
